# Modified conf/data_catalog/local.yml
datasets:
  raw:
    theme_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Theme_list.csv
      driver_params: {}

    theme_product_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Theme_product_list.csv
      driver_params: {}

    product_manufacturer_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/product_manufacturer_list.csv
      driver_params: {}

    google_search_data:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/google_search_data.csv
      driver_params: {}

    sales_data:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales_data.csv
      driver_params: {}

    social_media_data:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/social_media_data.csv
      driver_params: {}

  cleaned:
    theme_list:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/theme_list.parquet
      driver_params: {}

    theme_product_list:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/theme_product_list.parquet
      driver_params: {}

    product_manufacturer_list:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/product_manufacturer_list.parquet
      driver_params: {}

    google_search_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/google_search_data.parquet
      driver_params: {}

    sales_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/sales_data.parquet
      driver_params: {}

    social_media_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/social_media_data.parquet
      driver_params: {}

    combined_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/combined_data.parquet
      driver_params: {}

  processed:
    combined_data:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/combined_data.parquet
      driver_params: {}

  train:
    analytics:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/analytics/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/analytics/target.parquet
        driver_params:
          save:
            index: False
  test:
    analytics:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/analytics/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/analytics/target.parquet
        driver_params:
          save:
            index: False
  score:
    analytics:
      output:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/analytics/scored_output.parquet
        driver_params:
          save:
            index: False